### ISSUE TITLE
json import call breaks python 2.5

### ISSUE THREAD

**Issue by yawpitch** [fdouetteau/bottle-mongodb-plugin#2]
I know that Python 2.5 isn't the most necessary thing to support anymore, but we're using mongo db and bottle at my work and, due to embedded versions of python in various desktop apps, we need to occasionally support 2.5.  If you changed the:

from json import dumps as json_dumps

to:

try:
  from json import dumps as json_dumps
except ImportError:
  from simplejson import dumps as json_dumps

It would at least use the fallback that wasn't introduced until 2.6.  I don't see any obvious other issues with your code and 2.6.

**Comment by fdouetteau** [comment]
Indeed ! just fixed it.

**Comment by yawpitch** [comment]
That's great Florian, thanks!

## 

END OF LINE
